### ISSUE TITLE
Testing fails

### ISSUE THREAD

**Issue by vkarihal** [google-research/arxiv-latex-cleaner#86]
I ran this command 
**python -m unittest arxiv_latex_cleaner.tests.arxiv_latex_cleaner_test**
 and four unit test failed.
![Screenshot from 2024-01-12 21-17-45](https://github.com/google-research/arxiv-latex-cleaner/assets/8115746/e18af3a8-3a41-4e7c-9a19-090b009138da)

Also when I try to run arxiv_latex_cleaner to make my latex files compatible to arxiv, it fails for the **case  out_folder = os.path.abspath(input_folder).removesuffix('.zip') + '_arXiv'
AttributeError: 'str' object has no attribute 'removesuffix'** which it fails for when running the unittest command.

**Comment by jponttuset** [comment]
Hi @vkarihal 
I've just tried running the tests both in Mac and Linux and they didn't fail.
Can you try running the following?

```
pip install -r requirements.txt
```

What platform are you running on?

**Comment by jponttuset** [comment]
I just realized that you're running with Python 3.8 but `removesuffix ` needs 3.9+.
I'll make this clearer in the README.

**Comment by vkarihal** [comment]
output of the command : pip install -r requirements.txt

![Screenshot from 2024-02-05 19-36-47](https://github.com/google-research/arxiv-latex-cleaner/assets/8115746/0abfa18d-63d5-4afd-a767-699721660316)

What platform  are you running on?

![Screenshot from 2024-02-05 19-38-00](https://github.com/google-research/arxiv-latex-cleaner/assets/8115746/7b00eb4e-256a-480b-a06b-0728e9ac3483)

Are you synced to head ?-
(a) i did a "pip install" as mentioned in the documentation
(b) i downloaded from git and used it.

I just realized that you're running with Python 3.8 but removesuffix needs 3.9+

I too believe the same. it worked fine on a macbook with python 3.9+. I was using anaconda in my ubuntu machine, not sure if that had some part in messing it up.

Thank you
